"""add quantity on hand to materials

Revision ID: 2214a3da90ae
Revises: c3a0b56f77b4
Create Date: 2026-05-18 21:50:54.934846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2214a3da90ae'
down_revision: Union[str, Sequence[str], None] = 'c3a0b56f77b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('quantity_on_hand', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'quantity_on_hand')
    # ### end Alembic commands ###
