"""add dimensions to products

Revision ID: 6781d4495d5e
Revises: 6ebaa0c41fff
Create Date: 2026-05-18 16:46:01.681163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6781d4495d5e'
down_revision: Union[str, Sequence[str], None] = '6ebaa0c41fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('depth', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'depth')
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    # ### end Alembic commands ###
