"""add product and quantity to manufacturing orders

Revision ID: 6ebaa0c41fff
Revises: ff112f7e9e06
Create Date: 2026-05-18 16:34:37.524024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebaa0c41fff'
down_revision: Union[str, Sequence[str], None] = 'ff112f7e9e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturing_orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('manufacturing_orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'manufacturing_orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturing_orders', type_='foreignkey')
    op.drop_column('manufacturing_orders', 'quantity')
    op.drop_column('manufacturing_orders', 'product_id')
    # ### end Alembic commands ###
