"""add quantity on hand to materials

Revision ID: b19eeac1979c
Revises: 2214a3da90ae
Create Date: 2026-05-18 21:57:25.462069

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'b19eeac1979c'
down_revision: Union[str, Sequence[str], None] = '2214a3da90ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
