"""add unit cost to materials

Revision ID: c3a0b56f77b4
Revises: 12f203c65d3c
Create Date: 2026-05-18 20:15:27.954334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a0b56f77b4'
down_revision: Union[str, Sequence[str], None] = '12f203c65d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('unit_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'unit_cost')
    # ### end Alembic commands ###
